[[mgr.prepend_keymap]]
on   = ["~"]
run  = "cd ~"
desc = "cd to ~"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "enter"
desc = "Enter the child directory"

[[mgr.prepend_keymap]]
on = "/"
run = "filter --smart"
desc = "Filter files"

[[mgr.prepend_keymap]]
on   = ["g", "p"]
run  = "cd ~/Code/projects"
desc = "Go to Projects"

[[mgr.prepend_keymap]]
on   = ["g", "c"]
run  = "cd ~/.local/configs/dotfiles/"
desc = "Go to dotfiles"

[[mgr.prepend_keymap]]
on   = ["g", "n"]
run  = "cd ~/Documents/personal_notes"
desc = "Go to Noters"

[[mgr.prepend_keymap]]
on   = ["g", "m"]
run  = "cd ~/snapbox/oew/app/wp-content/microservice/internal/services/thread_manager/"
desc = "Go to Microservice"

[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = "cd ~/snapbox/oew/app/wp-content/plugins/otew-features/fwpages/react/"
desc = "Go to Noters"
